#!/usr/bin/env python
"""Regenerate days/INDEX.md - a catalogue of every written part document.

`ls` is the table of contents for one day (plan Part 11). This is the table of
contents for all of them: one row per part, so the question "has this idea been
taught already, and where" is answerable without opening a part body. Reading
days/ to answer it costs about 790 000 tokens; reading this costs about 6 000.

Every cell is COPIED from the eight frontmatter keys the depth contract already
mandates on every part. Nothing is summarised or generated, so this file cannot
disagree with the parts it indexes - if it does, the frontmatter is wrong and
`./m depth` is the thing that says so.

    uv run python scripts/parts_index.py      # rewrite days/INDEX.md
    ./m tracker                               # rewrites the tracker and this
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DAYS = ROOT / "days"
INDEX = DAYS / "INDEX.md"

FRONTMATTER_RE = re.compile(r"^(\w+):\s*(.*)$", re.M)
# Curriculum IDs as the plan writes them: two to four capitals, a hyphen, digits.
ID_RE = re.compile(r"[A-Z]{2,4}-\d+")


def frontmatter(path: Path) -> dict[str, str]:
    """The part's frontmatter block as a dict - the only thing this script reads."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    block = text.split("---")[1]
    return {k: v.strip().strip('"') for k, v in FRONTMATTER_RE.findall(block)}


def build() -> tuple[str, int, int]:
    rows: list[str] = [
        "---",
        "name: parts-index",
        "plan: setu",
        f'generated: "{date.today().isoformat()}"',
        "generator: scripts/parts_index.py",
        "---",
        "",
        "# 🗂️ Parts index — every written sub-topic document",
        "",
        "> **Do not edit this file by hand.** It is regenerated by `./m tracker` from the "
        "frontmatter of every part under `days/day-NN-<slug>/parts/`. Every cell is copied; "
        "nothing here is written independently of the parts themselves.",
        "",
        "> **What this is for.** One row per part document, so you can find where an idea was "
        "already taught — and link to it rather than explaining it twice (plan Part 11, the "
        "standalone test). The second table inverts it: which parts serve a curriculum ID.",
        "",
    ]

    by_id: dict[str, list[str]] = {}
    day_count = 0
    part_count = 0

    for folder in sorted(DAYS.glob("day-*")):
        parts = sorted(folder.glob("parts/*/*.md"))
        if not parts:
            continue
        day_count += 1
        rows += [
            f"## `{folder.name}` — {len(parts)} parts",
            "",
            "| Part | Level | Title | IDs | File |",
            "|---|---|---|---|---|",
        ]
        for path in parts:
            keys = frontmatter(path)
            relative = path.relative_to(DAYS).as_posix()
            rows.append(
                f"| {keys.get('part', '?')} | {keys.get('level', '?')} "
                f"| {keys.get('title', '?')} | {keys.get('ids', '')} "
                f"| [`{path.parent.name}/{path.name}`]({relative}) |"
            )
            part_count += 1
            for curriculum_id in ID_RE.findall(keys.get("ids", "")):
                # Day and part number only. The path is already one table up, and repeating
                # 141 of them here cost more than the whole rest of the file.
                by_id.setdefault(curriculum_id, []).append(
                    f"{keys.get('day', '?')}.{keys.get('part', '?')}"
                )
        rows.append("")

    rows += [
        "## Curriculum ID → the parts that teach it",
        "",
        "> Every ID the plan slots to a written day should appear here. An ID that a day claims "
        "in its hub but that no part carries in its frontmatter is the gap this table exposes. "
        "Entries are `day.part` — find the file in that day's table above.",
        "",
        "| ID | Parts | Taught in |",
        "|---|---|---|",
    ]
    for curriculum_id in sorted(by_id):
        where = by_id[curriculum_id]
        rows.append(f"| `{curriculum_id}` | {len(where)} | {' · '.join(where)} |")
    rows.append("")

    return "\n".join(rows) + "\n", day_count, part_count


def main() -> int:
    content, days, parts = build()
    INDEX.write_text(content, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT).as_posix()} - {parts} parts across {days} days")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
